In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("nursery.data",header=None)

In [3]:
df.head()

0       1         2  3           4           5              6  \
0  usual  proper  complete  1  convenient  convenient        nonprob   
1  usual  proper  complete  1  convenient  convenient        nonprob   
2  usual  proper  complete  1  convenient  convenient        nonprob   
3  usual  proper  complete  1  convenient  convenient  slightly_prob   
4  usual  proper  complete  1  convenient  convenient  slightly_prob   

             7          8  
0  recommended  recommend  
1     priority   priority  
2    not_recom  not_recom  
3  recommended  recommend  
4     priority   priority

In [4]:
df[2].unique()

array(['complete', 'completed', 'incomplete', 'foster'], dtype=object)

In [6]:
df.columns =  [["Parents","has_nurs","form","children","housing","finance","social","health","Target"]]

In [15]:
df = df["Target"]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12960 entries, 0 to 12959
Data columns (total 9 columns):
(Parents,)     12960 non-null object
(has_nurs,)    12960 non-null object
(form,)        12960 non-null object
(children,)    12960 non-null object
(housing,)     12960 non-null object
(finance,)     12960 non-null object
(social,)      12960 non-null object
(health,)      12960 non-null object
(Target,)      12960 non-null object
dtypes: object(9)
memory usage: 911.3+ KB


In [7]:
X = df.drop("Target",axis=1)
y = df["Target"]

C:\Users\Tanay Shah\Anaconda3\lib\site-packages\pandas\core\generic.py:3812: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  new_axis = axis.drop(labels, errors=errors)


In [15]:
X = pd.get_dummies(X)
X

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12960 entries, 0 to 12959
Data columns (total 27 columns):
('Parents',)_great_pret      12960 non-null uint8
('Parents',)_pretentious     12960 non-null uint8
('Parents',)_usual           12960 non-null uint8
('has_nurs',)_critical       12960 non-null uint8
('has_nurs',)_improper       12960 non-null uint8
('has_nurs',)_less_proper    12960 non-null uint8
('has_nurs',)_proper         12960 non-null uint8
('has_nurs',)_very_crit      12960 non-null uint8
('form',)_complete           12960 non-null uint8
('form',)_completed          12960 non-null uint8
('form',)_foster             12960 non-null uint8
('form',)_incomplete         12960 non-null uint8
('children',)_1              12960 non-null uint8
('children',)_2              12960 non-null uint8
('children',)_3              12960 non-null uint8
('children',)_more           12960 non-null uint8
('housing',)_convenient      12960 non-null uint8
('housing',)_critical        12960 non-nu

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [18]:
from sklearn.svm import SVC

In [19]:
svc = SVC(kernel="linear")

In [20]:
svc.fit(X_train,y_train)

C:\Users\Tanay Shah\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [56]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3888 entries, 8327 to 6561
Data columns (total 27 columns):
('Parents',)_great_pret      3888 non-null uint8
('Parents',)_pretentious     3888 non-null uint8
('Parents',)_usual           3888 non-null uint8
('has_nurs',)_critical       3888 non-null uint8
('has_nurs',)_improper       3888 non-null uint8
('has_nurs',)_less_proper    3888 non-null uint8
('has_nurs',)_proper         3888 non-null uint8
('has_nurs',)_very_crit      3888 non-null uint8
('form',)_complete           3888 non-null uint8
('form',)_completed          3888 non-null uint8
('form',)_foster             3888 non-null uint8
('form',)_incomplete         3888 non-null uint8
('children',)_1              3888 non-null uint8
('children',)_2              3888 non-null uint8
('children',)_3              3888 non-null uint8
('children',)_more           3888 non-null uint8
('housing',)_convenient      3888 non-null uint8
('housing',)_critical        3888 non-null uint8
('housin

In [71]:
pred = svc.predict(X_test)

In [73]:
pred

array(['not_recom', 'not_recom', 'not_recom', ..., 'spec_prior',
       'priority', 'priority'], dtype=object)

In [74]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [75]:
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.9272119341563786
              precision    recall  f1-score   support

   not_recom       1.00      1.00      1.00      1328
    priority       0.88      0.90      0.89      1295
  spec_prior       0.90      0.89      0.90      1170
  very_recom       0.87      0.68      0.76        95

   micro avg       0.93      0.93      0.93      3888
   macro avg       0.91      0.87      0.89      3888
weighted avg       0.93      0.93      0.93      3888

[[1328    0    0    0]
 [   0 1171  114   10]
 [   0  129 1041    0]
 [   0   30    0   65]]


In [76]:
from sklearn.tree import DecisionTreeClassifier

In [77]:
dtree = DecisionTreeClassifier()

In [78]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [79]:
pred_tree = dtree.predict(X_test)

In [80]:
print(accuracy_score(y_test,pred_tree))
print(classification_report(y_test,pred_tree))
print(confusion_matrix(y_test,pred_tree))

0.9963991769547325
              precision    recall  f1-score   support

   not_recom       1.00      1.00      1.00      1328
    priority       0.99      1.00      0.99      1295
  spec_prior       1.00      0.99      1.00      1170
  very_recom       0.98      0.98      0.98        95

   micro avg       1.00      1.00      1.00      3888
   macro avg       0.99      0.99      0.99      3888
weighted avg       1.00      1.00      1.00      3888

[[1328    0    0    0]
 [   0 1291    2    2]
 [   0    8 1162    0]
 [   0    2    0   93]]


In [82]:
from sklearn.externals import joblib

In [83]:
joblib.dump(dtree,"dtree.sav")

['dtree.sav']

In [86]:
filename = "dtree.sav"
dtree = joblib.load(filename)
res = dtree.predict([final])
res[0]

'not_recom'